name: Build binary

on:
  push:
    tags:
      - v**
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        job:
          - { os: ubuntu-latest }


    name: Build
    runs-on: ${{ matrix.job.os }}
    steps:
      # - uses: actions/checkout@v2
      # - uses: actions-rs/toolchain@v1
      #   with:
      #     profile: minimal
      #     toolchain: stable
      #     override: true
      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release
      - name: Rename binary
        id: rename
        shell: bash
        run: |
          if [[ $GITHUB_REF == *"beta"* ]]; then
            PRERELEASE=true
          else
            PRERELEASE=false
          fi
          echo "prerelease: $PRERELEASE"
          echo "::set-output name=bin::target/release/$BIN"
          echo "::set-output prerelease=${{ toJSON($PRERELEASE) }}"
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: artifact
      #     path: |
      #       target/release/file_duplicate_checker_*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          #files: ${{ steps.rename.outputs.bin }}
          prerelease: fromJSON(steps.rename.outputs.prerelease)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
